<?php

require dirname(__DIR__) . '/vendor/autoload.php';

$root = dirname(__DIR__);
$output = "# Generated source reference\n\nGenerated by `php tools/reference.php`; do not edit by hand.\n\nThis indexes declared public methods, not a promise of API stability.\nSchema details (columns, indexes, FKs) remain authoritative in linked migrations.\n";
foreach (array_merge([$root], glob($root . '/packages/*', GLOB_ONLYDIR)) as $directory) {
    $label = $directory === $root ? 'Core' : basename($directory);
    $output .= "\n## {$label}\n\n### Migrations\n\n";
    foreach (glob($directory . '/database/migrations/*.php') as $file) {
        $relative = str_replace('\\', '/', substr($file, strlen($root) + 1));
        preg_match_all("/Schema::(?:create|table)\\('([^']+)'/", file_get_contents($file), $tables);
        $output .= '- [' . basename($file) . '](../' . $relative . '): ' . implode(', ', array_unique($tables[1])) . "\n";
    }
    $output .= "\n### Services and contracts\n\n";
    foreach (['Services', 'Contracts'] as $folder) {
        $files = glob($directory . '/src/' . $folder . '/*.php');
        foreach ($files as $file) {
            $source = file_get_contents($file);
            if (! preg_match('/namespace ([^;]+);/', $source, $namespace)) {
                continue;
            }
            $class = $namespace[1] . '\\' . basename($file, '.php');
            $reflection = new ReflectionClass($class);
            $relative = str_replace('\\', '/', substr($file, strlen($root) + 1));
            $output .= '- [' . $class . '](../' . $relative . ")\n";
            foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
                if ($method->getDeclaringClass()->getName() !== $class || $method->isConstructor()) {
                    continue;
                }
                $parameters = [];
                foreach ($method->getParameters() as $parameter) {
                    $parameters[] = ($parameter->hasType() ? $parameter->getType() . ' ' : '')
                        . '$' . $parameter->getName() . ($parameter->isOptional() ? ' [optional]' : '');
                }
                $output .= '  - `' . $method->getName() . '(' . implode(', ', $parameters) . ')'
                    . ($method->hasReturnType() ? ': ' . $method->getReturnType() : '') . "`\n";
            }
        }
    }
}
if (in_array('--check', $argv, true)) {
    $path = $root . '/docs/SOURCE_REFERENCE.md';
    if (! is_file($path) || str_replace("\r\n", "\n", file_get_contents($path)) !== $output) {
        fwrite(STDERR, "Source reference is stale. Regenerate using php tools/reference.php.\n");
        exit(1);
    }
    exit(0);
}
echo $output;
